# Setup
# - put/symlink this file in ~/.config/starship.toml



[hostname]
ssh_only = true

[username]
show_always = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 0

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](red)'


[aws]
disabled = true

[cmd_duration]
disabled = true
