abbr --add gst "git status"
abbr --add gcb "git checkout -b"
abbr --add ga "git add"
abbr --add gaa "git add --all"
abbr --add gdca "git diff --cached"
abbr --add gcm "git commit -m"
abbr --add ggpush "git push origin HEAD"
abbr --add ggpull "git pull origin HEAD"
abbr --add gdl "git diff HEAD~ HEAD"
abbr --add gbd "git branch -d"
abbr --add gcam "git commit --amend"
abbr --add gcam! "git commit --amend --no-edit"

