abbr --add gst 'git status'
abbr --add gcb 'git checkout -b'
abbr --add ga 'git add'
abbr --add gaa 'git add --all'
abbr --add gd 'git diff'
abbr --add gdca 'git diff --cached'
abbr --add gcm 'git commit -m'
abbr --add ggpush 'git push origin (git rev-parse --abbrev-ref HEAD)'
abbr --add ggpull 'git pull origin (git rev-parse --abbrev-ref HEAD)'
abbr --add gdl 'git diff HEAD~ HEAD'
abbr --add gbd 'git branch -d'
abbr --add gcam 'git commit --amend'
abbr --add gcam! 'git commit --amend --no-edit'
abbr --add gb 'git branch'
abbr --add gco 'git checkout'
abbr --add gcom 'git checkout master'
# git log abbreviation intentionally excluded until I have a favourite invokation
abbr --add gfa 'git fetch --all --prune'
